services:
  traefik:
    image: traefik:v2.9
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4G
    command:
      - --configFile=/traefik_data/config.yaml

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - 80:80
      - 443:443

      # Dashboard only on localhost
      - 127.0.0.1:8080:8080
    volumes:
      - ./traefik_data:/traefik_data
