accessLog:
  filePath: /opt/jupyterhub/traefik/access.log
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        Content-Type: keep

log:
  filePath: /opt/jupyterhub/traefik/traefik.log
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls: true

certificatesResolvers:
  letsencrypt:
    acme:
      httpchallenge:
        entrypoint: web
      email: sysadmin@molssi.org
      storage: /opt/jupyterhub/traefik/acme.json

providers:
  file:
    filename: /opt/jupyterhub/traefik/jhub_config.yaml
    watch: true
